# Generated by Django 5.1.4 on 2024-12-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primewheelsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.ManyToManyField(related_name='vehicles', to='primewheelsapp.feature'),
        ),
    ]
